services:
  openwebui:
    build:
      context: ./webui
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    networks:
      - mars-network

  sber-wrapper:
    build:
      context: ./sber_wrapper
      dockerfile: Dockerfile
    ports:
      - "8501:8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - mars-network

networks:
  mars-network:
    driver: bridge

volumes:
  open-webui:
