name: mars-webui
services:
  openwebui:
    container_name: mars-openwebui
    build:
      context: ./webui
      dockerfile: Dockerfile
      network: host  # Add this line
    ports:
      - "3000:8080"
    volumes:
      - mars-webui-data:/app/backend/data
    networks:
      - mars-network
    pull_policy: always  # Add this line

  sber-wrapper:
    container_name: mars-sber-wrapper
    build:
      context: ./sber_wrapper
      dockerfile: Dockerfile
      network: host  # Add this line
    ports:
      - "8501:8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - mars-network
    pull_policy: always  # Add this line

networks:
  mars-network:
    name: mars-network
    driver: bridge

volumes:
  mars-webui-data:
    name: mars-webui-data