name: mars-webui
services:
  openwebui:
    image: doc4duck/mars-openwebui:latest
    ports:
      - "3000:8080"
    volumes:
      - mars-webui-data:/app/backend/data
    networks:
      - mars-network
    pull_policy: always

  sber-wrapper:
    image: doc4duck/sber-wrapper:latest
    ports:
      - "8501:8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - mars-network
    pull_policy: always

networks:
  mars-network:
    name: mars-network
    driver: bridge

volumes:
  mars-webui-data:
    name: mars-webui-data