name: mars-webui  # Add this line at the top

services:
  openwebui:
    container_name: mars-openwebui  # Add explicit container name
    build:
      context: ./webui
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    volumes:
      - mars-webui-data:/app/backend/data  # Rename volume
    networks:
      - mars-network

  sber-wrapper:
    container_name: mars-sber-wrapper  # Add explicit container name
    build:
      context: ./sber_wrapper
      dockerfile: Dockerfile
    ports:
      - "8501:8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - mars-network

networks:
  mars-network:
    name: mars-network  # Add explicit network name
    driver: bridge

volumes:
  mars-webui-data:  # Rename volume
    name: mars-webui-data  # Add explicit volume name